version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tasklist:3306/task_list_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: PROD
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-tasklist
    restart: always
    environment:
      MYSQL_DATABASE: task_list_service
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
